version: "3.9"
services:
  dashboard:
    build:
      context: .
      dockerfile: ./dockerfile
    image: superset_df_dashboard
    ports:
      - "8088:8088"
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5432:5432'
  clickhouse:
    image: yandex/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - '8123:8123'